version: '3.8'

services:
  postgresql:
    image: postgres:latest
    ports: 
      - "5433:5433"
    expose:
      - "5433"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb

